install:
	mkdir -p /etc/tsar/conf.d/
	cp ./mod_lua_nginx.lua /usr/local/tsar/modules/
	cp ./mod_lua_nginx.conf /etc/tsar/conf.d/lua_nginx.conf

uninstall:
	rm /usr/local/tsar/modules/mod_lua_nginx.lua
	rm /etc/tsar/conf.d/lua_nginx.conf
